apiVersion: v1
kind: Service
metadata:
  name: gitlab-gitlab-node-port
spec:
  selector:
    name: gitlab-gitlab
  ports:
  - name: ssh
    port: 22
    nodePort: 31000
    targetPort: 22
  - name: gitlab
    port: 8005
    nodePort: 30000
    targetPort: 8005
  - name: registry
    port: 8105
    nodePort: 32000
    targetPort: 8105
  type: NodePort
