apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitlab-self-host-registry
  labels:
    app: gitlab-self-host-registry
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gitlab-self-host-registry
        name: gitlab-self-host-registry
    spec:
      containers:
      - name: registry
        image: registry:2
        imagePullPolicy: IfNotPresent
        env:
        - name: REGISTRY_AUTH
          value: htpasswd
        - name: REGISTRY_AUTH_HTPASSWD_REALM
          value: Registry Realm
        - name: REGISTRY_AUTH_HTPASSWD_PATH
          value: "/auth/htpasswd"
        ports:
        - name: registry
          containerPort: 5000
        volumeMounts:
        - name: registry
          subPath: data
          mountPath: /var/lib/registry
        - name: registry
          subPath: auth
          mountPath: /auth
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 1800
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 15
          timeoutSeconds: 2
      volumes:
      - name: registry
        persistentVolumeClaim:
          claimName: gitlab-self-host-registry-storage
